name: Build and Publish Music (Pages)

on:
  schedule:
    - cron: '12 6 * * *'  # daily 06:12 UTC
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Show repo layout (handy when debugging)
      - name: Show repo layout
        run: |
          pwd
          ls -la
          echo "All csproj files:"
          find . -maxdepth 4 -name "*.csproj" -print

      # Find the worker project dynamically
      - name: Locate worker csproj
        id: locate
        run: |
          set -euo pipefail
          csproj="$(find "$GITHUB_WORKSPACE" -maxdepth 4 -name 'MusicPage.Worker.csproj' | head -n1)"
          if [ -z "$csproj" ]; then
            echo "Could not find MusicPage.Worker.csproj" >&2
            find . -maxdepth 6 -name '*.csproj' -print
            exit 1
          fi
          echo "Found: $csproj"
          echo "csproj=$csproj" >> "$GITHUB_OUTPUT"
          echo "projdir=$(dirname "$csproj")" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore "${{ steps.locate.outputs.csproj }}"

      - name: Build
        run: dotnet build "${{ steps.locate.outputs.csproj }}" --configuration Release --no-restore

      - name: Run music worker
        working-directory: ${{ steps.locate.outputs.projdir }}
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_FOLDER: '/Public/Tracks'
          OUTPUT_DIR: out
        run: dotnet run -c Release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.locate.outputs.projdir }}/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
